name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Yeh build process ko safe aur fast rakhega

      - name: Install Dependencies
        run: npm install

      - name: Build with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon -x lint -x test

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Drapii-App-APK
          path: android/app/build/outputs/apk/release/*.apk
